// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layout/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layout/BaseSide/index.vue')['default']
    BaseSideItem: typeof import('./components/layout/BaseSide/BaseSideItem.vue')['default']
    Breadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Hamburger: typeof import('./components/layout/Hamburger.vue')['default']
    HelloI18n: typeof import('./components/HelloI18n.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./components/layout/TagsView/ScrollPane.vue')['default']
    TagsView: typeof import('./components/layout/TagsView/index.vue')['default']
  }
}

export {}
